### ISSUE TITLE
Unconfirmed possible bookmark corruption - Unconfirmed

### ISSUE THREAD

**Issue by Gitoffthelawn** [antoyo/auto-sort-bookmarks#21]
I put "Unconfirmed" in the title twice (and "possible" once!) because I don't want anyone to get unnecessarily concerned.  There is a very reasonable chance there is **no problem at all** with this extension.

I experienced some minor bookmark corruption.  I lost only 1 bookmark.  I do not know if it is a bug in Firefox or this extension.

I've experienced some issues with Firefox lately regarding bookmark corruption for bookmarks with keywords.  I have not lost any bookmarks that do not have keywords (to my knowledge).

I wish I could give you the steps to reproduce the issue, but I am too pressed for time to run through all the different possibilities in order to properly diagnose the issue.  What I do have time to do is to share with you my experience: I went to the Bookmarks Library, and noticed that one of the bookmarks had no favicon at all (not even a blank placeholder one). Even though I could select its row in the Bookmarks Library, none of the fields in the bottom of the Bookmarks Library window would update as they should.  It was clear that something was corrupt.  I then remembered that the damaged bookmark had a keyword that I recently assigned to another bookmark.  Somewhere in that process, I believe I ran a manual sort using Auto-Sort Bookmarks.

Realizing that corruption was present, I performed an export filed by an import.  I only lost that one bookmark, from what I could tell.

**Comment by antoyo** [comment]
This is unlikely to be a problem with this extension (except if there is a bug in one of the API used), because I try to keep the number of changes to the bookmarks to the minimum.
Currently, I only update the index of the bookmarks (and, as far as I remember, a wrong index throws an error so the sorting would not work in this case) and add/remove annotations on them.
However, the recent versions of this add-on now moves the corrupted bookmarks at the end position in its folder. This is to fix the issue #7. And, since Firefox have some trouble showing corrupted bookmarks (at least in the toolbar), perhaps the corrupted bookmarks are still in the Firefox places database.
You can try to look into the `places.sqlite` file to see if you can recover your lost bookmarks.

**Comment by Gitoffthelawn** [comment]
Thanks.  I tend to think it is a Firefox bug, but I want to make you (and everyone else) aware of the issue in case others experience it as well (and in the slim case that it is caused by this extension).  Perhaps with more data, the bug can be fully reported and fixed.
