### ISSUE TITLE
jpm: icon issue

### ISSUE THREAD

**Issue by TheRealMarnes** [antoyo/auto-sort-bookmarks#22]
Just FYI, when building addons with jpm, you need to open the compiled addon and remove the icon entry from install.rdf before uploading to amo because firefox *still* doesn't display it correctly. It looks like mozilla doesn't give a flying fuck about fixing this, as usual: https://bugzilla.mozilla.org/show_bug.cgi?id=1141839.

Thanks for updating to jpm though, progress is good

**Comment by antoyo** [comment]
Thanks for reporting this issue.
As you may have noticed, I am looking for someone to maintain this add-on.
I will not update it anymore.
This issue will be fixed if I find someone.

**Comment by TheRealMarnes** [comment]
I'm a fan of this addon and may be able to help, but I don't think I can say I'd just take it over :/

**Comment by antoyo** [comment]
If you know JavaScript and you want to contribute I will help you by telling you what you need to know to maintain this add-on.
You may also just do compatibility fixes (and small fixes like this one) if you want, waiting for someone else take it over.

**Comment by TheRealMarnes** [comment]
Well I have a dozen of my own addons, so yes, I think I know JS :P I'm mostly iffy about working with a bookmark addon while I have 0 experience with the code involving the bookmarks subsystem, related events and exceptions, possible weirdness and glitches, etc. I'd love to help out but I'm finding myself short on time and motivation for even my own work. Your code style is heavy on documentation and verboseness too, I'm more a man of few words and compacted lines...

**Comment by Gitoffthelawn** [comment]
Such a great extension... I hope it is maintained.

**Comment by TheRealMarnes** [comment]
(I'm a little unfamiliar with github power use, so walk me through this) Let's say hypothetically I fork your project, to check out the code, try to get a hold on it, maybe update parts of it. What did you have in mind for your successor to do in terms of continuing? Forking, handing over the repo, ... ? To which extent do you want the code and code style to remain the same? Used tools (I don't use jshint and whatnot, for example).

**Comment by antoyo** [comment]
Forking can be an option, but I though of adding the one as contributor to this repository and to the [AMO site][1] add-on's page.
That's what I did for someone, but, unfortunately, I did not have any news from him for 3 weeks…

I don't care about the code style and the tests.
Some tests even started to fail after Firefox updates.
So, you'll be free of doing whatever you want.

I haven't used Firefox for more than a year, but I updated the add-on anyway because there are some many users.
However, I cannot continue, as I have other projects to work on.
That's why the maintener(s) will be free of doing the development the way (s)he wants.

I'll try to create a wiki page to share as much information as possible about the design decisions and release process soon so that everybody can get more information (a big part of it is already done because I sent this information to the person that contacted be, but this is in french, so I need to translate it).

[1]: https://addons.mozilla.org/firefox/

**Comment by antoyo** [comment]
Perhaps we should continue the discussion in issue #23 to avoid writing irrelevant data in this issue.

**Comment by antoyo** [comment]
@TheRealMarnes I think we could close this, right?

**Comment by TheRealMarnes** [comment]
Oh, yes, right, I fixed it yesterday

**Comment by antoyo** [comment]
Thanks for your first contribution on this project :) .

**Comment by TheRealMarnes** [comment]
It was a minor thing, just paperwork really :P
