### ISSUE TITLE
Help with auto-sort

### ISSUE THREAD

**Issue by bonneyarmstrong** [antoyo/auto-sort-bookmarks#23]
Would be willing to help with maintenance if needed.

**Comment by antoyo** [comment]
Great.
Do you know JavaScript?
I'll create a wiki page as soon as possible (hopefully tomorrow) to share information about the design decisions and the release process so that you get as much information as possible to help you to get started.
If you have any question, feel free to ask.
Thanks for your interest.

**Comment by bonneyarmstrong** [comment]
Yes. I want to learn more and get more hands-on with Firefox plug-in
development; thought this would be a good way to get my feet wet.

**Comment by antoyo** [comment]
Hi.
I made this [wiki page][1] to provide you all information you need about the design decisions and process of this add-on.

Please read this page first.

If you are still interested, I'll add you as a contributor.

Then, you could start with this [little issue][2].

Thanks again for your interest.

[1]: https://github.com/antoyo/auto-sort-bookmarks/wiki/Information-for-future-mainteners
[2]: https://github.com/antoyo/auto-sort-bookmarks/issues/22

**Comment by TheRealMarnes** [comment]
I'll stick around too and try to contribute, but for now just off the books, using diffs/pull requests/etc.

**Comment by antoyo** [comment]
Thanks @TheRealMarnes. Pull requests would be fine.

**Comment by TheRealMarnes** [comment]
Actually, I suppose just sign me up as contributor. I don't know when I'll be able to work on things but I am getting interested in it, starting with applying mozilla's preferred code style (arrow functions, consts, etc)

**Comment by antoyo** [comment]
I added you as a contributor on this Github project.

If you wish I could add you as an author on [AMO](https://addons.mozilla.org/fr/firefox/addon/auto-sort-bookmarks/) so that you can upload new versions. For this, you will need to send me the email you used to sign up on AMO (you can send it by mail if you prefer).

**Comment by TheRealMarnes** [comment]
That would be marnick.leau@gmail.com :) Thanks

**Comment by antoyo** [comment]
I added you as an author on AMO.
Thanks for your interest.

**Comment by Gitoffthelawn** [comment]
Thank you to everyone volunteering to help keep this project alive and strong!

I'll continue to report any bugs I find.  Due to the great coding, there have been very few! :)
