### ISSUE TITLE
No longer works with Firefox 43 because add-on is unsigned.

### ISSUE THREAD

**Issue by bulrush15** [antoyo/auto-sort-bookmarks#27]
Can you get this add-on signed? Firefox 43 now no longer allows any unsigned addons at all. FF disables all unsigned addons with no way to enable them.

**Comment by antoyo** [comment]
The add-on on the [Mozilla Add-ons website](https://addons.mozilla.org/en-US/firefox/addon/auto-sort-bookmarks/) is automatically signed.
I was able to install it in Firefox 44.

If it does not work for you, one way to install it is disabling add-on signature:

 * Enter the url `about:config` in Firefox.
 * Search for `xpinstall.signatures.required`.
 * Set this setting to false.

If you prefer installing only signed add-ons, you should ask Mozilla about this issue since this add-on **is** signed and I cannot do anything to help you since the signature process is done by Mozilla.

**Comment by Gitoffthelawn** [comment]
I can confirm the extension on AMO is properly signed.
